#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for rewrite
#
#
# Portions Copyright(C) 2010 Nippon Telegraph and Telephone Corporation
#
# IDENTIFICATION
#    src/backend/pgxc/plan/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/pgxc/plan
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = planner.o

include $(top_srcdir)/src/backend/common.mk
